#!/bin/bash

function date_fmt {
    date "+%H:%M:%S"
}

start_date=`date_fmt`
echo "Started: $start_date"
seconds=$(($1 * 60))
sleep $seconds
echo "Complete: `date_fmt`"

# Notify through UI.
if [ $2 ]; then
    title=$2
else
    title="Timebox complete"
fi
body_text="Slept $1 minutes starting at $start_date"


if [ $OSTYPE == 'linux-gnu' ]; then
    notify-send -u critical "$title" "$body_text"

else # Assuming macOS because shell is hard.
    # Notification isn't persistent so we have to loop.
    while true; do
        osascript -e "display notification \"$body_text\" with title \"$title\""
        sleep 15
    done
    echo "Stopped: `date_fmt`"
fi
